Medic outgoing registration dao service
palladiumkenya/openmrs-module-afyastat pull request #36
Opened 2022-02-11 11:07 UTC by PatrickWaweru

Added the DAO, service, service implementation and service config

2022-02-11 20:54 UTC, ojwanganto requested changes
This is good work, Patrick! Please address the few comments so that we review again.

2022-02-11 20:54 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/afyastat/api/db/MedicOutgoingRegistrationDao.java
> +	public List<MedicOutgoingRegistration> getRecordsByStatus(Integer status) {
Can we enforce an ordered result i.e first records to come at the top?

2022-02-11 20:54 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/afyastat/api/db/MedicOutgoingRegistrationDao.java
> +	public MedicOutgoingRegistration saveRecord(MedicOutgoingRegistration record) {
We are used to saveOrUpdate methods in OpenMRS. May be you can change the name to follow the convention.

2022-02-11 20:54 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/afyastat/api/service/MedicOutgoingRegistrationService.java
> +	@Authorized(AfyastatConfig.MODULE_PRIVILEGE)
Have you tested how this privilege works? 99% usage of the method will be through scheduler and a few times by users. Defining the privilege for the method would require that who/what invokes the method has the privilege. Please test it out and make any modifications

2022-02-15 08:20 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/afyastat/api/db/MedicOutgoingRegistrationDao.java
> +	public List<MedicOutgoingRegistration> getRecordsByStatus(Integer status) {
Done

2022-02-15 08:21 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/afyastat/api/db/MedicOutgoingRegistrationDao.java
> +	public MedicOutgoingRegistration saveRecord(MedicOutgoingRegistration record) {
Done

2022-02-15 08:22 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/afyastat/api/service/MedicOutgoingRegistrationService.java
> +	@Authorized(AfyastatConfig.MODULE_PRIVILEGE)
Tested and confirmed working for the schedulers.

2022-02-15 17:20 UTC, makombe commented on api/src/main/java/org/openmrs/module/afyastat/api/service/MedicOutgoingRegistrationService.java
> +	 * Returns an record by uuid. It can be called by any authenticated user. It is fetched in read
Should read 'Returns a record' not 'an record'

2022-02-17 05:17 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/afyastat/api/service/MedicOutgoingRegistrationService.java
> +	 * Returns an record by uuid. It can be called by any authenticated user. It is fetched in read
Done

2022-02-17 05:44 UTC, ojwanganto approved these changes

2022-02-17 05:46 UTC, merged