separated registration errors display from the other errors
palladiumkenya/openmrs-module-afyastat pull request #59
Opened 2022-04-20 11:52 UTC by PatrickWaweru

- separated registration errors display from the other errors, 
- fixed bug with all select checkbox
- better confirmation box using bootstrap

2022-04-21 05:35 UTC, ojwanganto requested changes

2022-04-21 05:35 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/afyastat/api/db/hibernate/HibernateInfoDao.java
> +	public List<T> getDataByDiscriminator(final String discriminator) {
Could we expand this to handle a list of discriminator String?

2022-04-21 05:35 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/afyastat/api/db/hibernate/HibernateInfoDao.java
> +	public List<T> getDataExceptByDiscriminator(final String discriminator) {
We can then abandon this since we will be passing a list of String

2022-04-21 05:35 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/afyastat/api/service/InfoService.java
> +	List<ErrorInfo> getAllRegistrationErrors();
Can we also pass a list of discriminator so that we keep just one method?

2022-04-22 03:37 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/afyastat/api/db/hibernate/HibernateInfoDao.java
> +	public List<T> getDataByDiscriminator(final String discriminator) {
done

2022-04-22 11:27 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/afyastat/api/db/hibernate/HibernateInfoDao.java
> +	public List<T> getDataExceptByDiscriminator(final String discriminator) {
Renamed to getDataExcludeDiscriminator.  This function is necessary to just search with exclusions.

2022-04-22 11:28 UTC, PatrickWaweru commented on api/src/main/java/org/openmrs/module/afyastat/api/service/InfoService.java
> +	List<ErrorInfo> getAllRegistrationErrors();
Since it is in the service class, this is ok to keep.

2022-04-27 21:47 UTC, merged